CREATE TABLE ROLE (
    ID serial NOT NULL,
    NAME varchar(50) UNIQUE NOT NULL,
    CONSTRAINT PK_ROLE PRIMARY KEY (ID)
);

CREATE TABLE ACCOUNT (
    ID serial NOT NULL,
    EMAIL varchar(255) UNIQUE  NOT NULL,
    PASSWORD varchar(255) NOT NULL,
    ENABLED boolean default false NOT NULL,
    ROLE_ID int NOT NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID),
    CONSTRAINT FK_ACCOUNT_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
);

CREATE TABLE CONFIRMATION_TOKEN (
    ID serial NOT NULL,
   	CREATED_DATE TIMESTAMP NOT NULL,
   	TOKEN varchar(255) NOT NULL,
   	ACCOUNT_ID int NOT NULL,
    CONSTRAINT PK_CONFIRMATION_TOKEN PRIMARY KEY (ID),
CONSTRAINT FK_CONFIRMATION_TOKEN_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID)
);

INSERT INTO ROLE(NAME) VALUES('USER');
INSERT INTO ROLE(NAME) VALUES('MANAGER');